FROM node:24-alpine

# SYSTEM

RUN apk add --no-cache zsh

# APP

WORKDIR /usr/src/app

COPY ./pnpm-lock.yaml ./workspaces/backends/nest-no-orm ./

RUN corepack enable && corepack prepare pnpm@latest --activate
RUN pnpm install
