version: "3"
set: [ pipefail ]

vars:
  REGISTRY_USER: cartok1337
  SERVICE_NAME: nest-no-orm
  CONTEXT_PATH: ../../../
  DOCKER_BUILD_FLAGS: '{{.DOCKER_BUILD_FLAGS | default ""}}'
  BASE_IMAGE: '{{.REGISTRY_USER}}/{{.SERVICE_NAME}}-base:latest'
  CODE_IMAGE: '{{.REGISTRY_USER}}/{{.SERVICE_NAME}}-code:latest'
  PROD_IMAGE: '{{.REGISTRY_USER}}/{{.SERVICE_NAME}}:latest'

tasks:
  # --- Build Tasks ---
  build:docker:base:
    cmds:
      - docker build -t {{.BASE_IMAGE}} -f docker/Dockerfile.base {{.CONTEXT_PATH}} {{.DOCKER_BUILD_FLAGS}}

  build:docker:base:no-cache:
    cmds:
      - task: build:docker:base
        vars: { DOCKER_BUILD_FLAGS: --no-cache }

  build:docker:code:
    deps: [build:docker:base]
    cmds:
      - docker build -t {{.CODE_IMAGE}} -f docker/Dockerfile.code {{.CONTEXT_PATH}} {{.DOCKER_BUILD_FLAGS}}

  build:docker:code:no-cache:
    cmds:
      - task: build:docker:code
        vars: { DOCKER_BUILD_FLAGS: --no-cache }

  build:docker:prod:
    deps: [build:docker:code]
    cmds:
      - docker build -t {{.PROD_IMAGE}} -f docker/Dockerfile.prod {{.CONTEXT_PATH}} {{.DOCKER_BUILD_FLAGS}}

  build:docker:
    cmds:
      - task: build:docker:prod

  # --- Publish Tasks ---
  publish:docker:
    deps: [build:docker]
    cmds:
      - docker push {{.BASE_IMAGE}}
      - docker push {{.CODE_IMAGE}}
      - docker push {{.PROD_IMAGE}}

  # --- Development Tasks ---
  dev:
    desc: Starts dependent services (like the DB) in Docker for local API development.
    cmds:
      - docker compose up -d
      - pnpm run start:dev

  dev:docker:
    # TODO: Permission management is complicated when trying to get API running in docker.
    # Needs further work.
    desc: Starts the full stack, including the API, inside Docker containers.
    cmds:
      - |
        docker compose \
        -f compose.yml \
        -f compose.dev.yml \
        --profile full \
        up \
        --build \
        --watch
