services:
  api:
    container_name: nest-no-orm-api
    build:
      context: ../../../../
      dockerfile: ./workspaces/backends/nest-no-orm/Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
    depends_on:
      - db

  db:
    image: postgres:18-alpine
    container_name: nest-no-orm-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
